name: Trigger auto deployment for yoop-backend-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: [main]
    paths:
      - "frontend/**"
      - ".github/workflows/yoop-frontend-app-AutoDeployTrigger.yml"

  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      #azure secrets needs to be generalized (currently ...BACKEND...)
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.YOOPBACKENDAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.YOOPBACKENDAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.YOOPBACKENDAPP_AZURE_SUBSCRIPTION_ID }}

      #azure secrets needs to be generalized (currently ...BACKEND...)
      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/frontend/**
          _dockerfilePathKey_: Dockerfile
          registryUrl: yoopacr.azurecr.io
          registryUsername: ${{ secrets.YOOPBACKENDAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.YOOPBACKENDAPP_REGISTRY_PASSWORD }}
          containerAppName: yoop-frontend-app
          resourceGroup: Yoop
          imageToBuild: yoopacr.azurecr.io/yoop-frontend-app:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_
