name: Trigger auto deployment for yoop-backend-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/yoop-backend-app-AutoDeployTrigger-ac5a24d1-47a0-4bcf-aa95-53a884ff70e1.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.YOOPBACKENDAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.YOOPBACKENDAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.YOOPBACKENDAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/backend
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: yoopacr.azurecr.io
          registryUsername: ${{ secrets.YOOPBACKENDAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.YOOPBACKENDAPP_REGISTRY_PASSWORD }}
          containerAppName: yoop-backend-app
          resourceGroup: Yoop
          imageToBuild: yoopacr.azurecr.io/yoop-backend-app:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


